DROP TABLE IF EXISTS STG_OPERSVODKA.STG_REFERENCE ;

CREATE TABLE IF NOT EXISTS STG_OPERSVODKA.STG_REFERENCE (
	SRC_SYSTEM VARCHAR(64) NOT NULL DEFAULT 'EXCEL FILE',
	SCENARIO VARCHAR(64) NOT NULL DEFAULT 'REFERENCE TABLE',
	BUSINESS_DT DATE NOT NULL DEFAULT GETDATE(),
	ID_PLANT_PRODUCT VARCHAR(64) NOT NULL,
	PLANT VARCHAR(12),
	PLANT_ENCRYPTED VARCHAR(12),
	PRODUCT VARCHAR(64),
	PLANT_PRODUCT VARCHAR(64),
	PLANT_PRODUCT_ENCRYPTED VARCHAR(64),
	FACTORY VARCHAR(12)
)
ORDER BY ID_PLANT_PRODUCT
SEGMENTED BY HASH(MD5(ID_PLANT_PRODUCT::VARCHAR)) ALL NODES
;
