CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_STG_STG_HQ_REPORT_DDS_HUB_DATE AS
SELECT DISTINCT
	MD5(TRIM(src.DT::VARCHAR)) AS HK_DDS_HUB_DATE ,
	fl.FILE_ID ,
	fl.LOAD_TS ,
	src.DT
FROM STG_OPERSVODKA.STG_STG_HQ_REPORT src
	INNER JOIN STG_OPERSVODKA.V_ETL_FILE_LOAD fl
			ON fl.SRC_SYSTEM = src.SRC_SYSTEM
				AND fl.FILE_NAME = src.SCENARIO
				AND fl.BUSINESS_DT = src.BUSINESS_DT
	LEFT JOIN ODS_OPERSVODKA.DDS_HUB_DATE trg
		ON MD5(TRIM(src.DT::VARCHAR)) = trg.HK_DDS_HUB_DATE
WHERE trg.HK_DDS_HUB_DATE IS NULL
;
