CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_HUB_DATE (
	HK_DDS_HUB_DATE VARCHAR(32) NOT NULL,
	FILE_ID INTEGER NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	DT DATE NOT NULL,
	PRIMARY KEY (HK_DDS_HUB_DATE) ENABLED
)
ORDER BY HK_DDS_HUB_DATE
SEGMENTED BY HASH(HK_DDS_HUB_DATE) ALL NODES
;
