CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_HST_DUMMY_CALENDAR AS
SELECT
	HK_DDS_HUB_DUMMY_CALENDAR ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	DATE_TODAY,
	DATE_DAY_BEFORE,
	DATE_MONTH_BEFORE,
	DATE_YEAR_BEFORE
FROM ODS_OPERSVODKA.DDS_HST_DUMMY_CALENDAR
LIMIT 1 OVER (PARTITION BY HK_DDS_HUB_DUMMY_CALENDAR ORDER BY LOAD_TS DESC)
;
