INSERT INTO ODS_OPERSVODKA.DDS_HST_PLANT_PRODUCT_REFERENCE (
	HK_DDS_HUB_PLANT_PRODUCT ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	PLANT_ENCRYPTED,
	PRODUCT,
	PLANT_PRODUCT,
	PLANT_PRODUCT_ENCRYPTED,
	FACTORY
)
SELECT
	HK_DDS_HUB_PLANT_PRODUCT ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	PLANT_ENCRYPTED,
	PRODUCT,
	PLANT_PRODUCT,
	PLANT_PRODUCT_ENCRYPTED,
	FACTORY
FROM ODS_OPERSVODKA.V_STG_REFERENCE_DDS_HST_PLANT_PRODUCT_REFERENCE src
;
