TRUNCATE TABLE ODS_OPERSVODKA.DM_DQ_MAIN;

-- отрабатывает долго(больше минуты из за добавления автоинкримента)
INSERT INTO ODS_OPERSVODKA.DM_DQ_MAIN (CHECK_NAME, CHECK_TYPE,CHECK_NUMBER,DT,PLANT_PRODUCT_ID,FACTORY,PLANT,PRODUCT,TYPE,VALUE,B_TYPE,B_VALUE,DELTA,COMMENT,ERR_TYPE)
SELECT reff.CHECK_NAME, reff.CHECK_TYPE,src.CHECK_NUMBER,cal.DT,src.PLANT_PRODUCT_ID,src.FACTORY,src.PLANT,src.PRODUCT,src.TYPE,src.VALUE,src.B_TYPE,src.B_VALUE,src.DELTA,src.COMMENT,src.ERR_TYPE  
FROM (select * from ODS_OPERSVODKA.DDS_CALENDAR where dt <= LAST_DAY(getdate()) and DATE_DAY_BEFORE is not NULL) cal
LEFT JOIN ODS_OPERSVODKA.DM_DQ_TEMP src ON cal.DT = src.DT
LEFT JOIN ODS_OPERSVODKA.DM_DQ_REFERENCE reff on reff.NUM = src.CHECK_NUMBER
ORDER BY cal.DT, src.CHECK_NUMBER, src.PLANT_PRODUCT_ID, src.TYPE;
