CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_HUB_COMMENTS (
	HK_DDS_HUB_COMMENTS VARCHAR(32) NOT NULL,
	FILE_ID INTEGER NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	ID VARCHAR(12) NOT NULL,
	DT DATE NOT NULL,
	PRIMARY KEY (HK_DDS_HUB_COMMENTS) ENABLED
)
ORDER BY HK_DDS_HUB_COMMENTS
SEGMENTED BY HASH(HK_DDS_HUB_COMMENTS) ALL NODES
;
