CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DM_PLANT_PRODUCT_METRIC_CALC (
	FILE_ID INT
	, LOAD_TS TIMESTAMP
	, DT DATE
	, ID_PLANT_PRODUCT VARCHAR(64)
	, FACTORY VARCHAR(12)
	, PLANT VARCHAR(12)
	, PRODUCT VARCHAR(64)
	, BP NUMERIC(18, 5) 
	, PLAN NUMERIC(18, 5) 
	, PPR NUMERIC(18, 5)
	, FORECAST NUMERIC(18, 5) 
	, FACT NUMERIC(18, 5)
	, PRIMARY KEY (DT, ID_PLANT_PRODUCT) ENABLED)
ORDER BY DT, ID_PLANT_PRODUCT 
SEGMENTED BY HASH(DT, ID_PLANT_PRODUCT) ALL NODES 
;