CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DM_OPER_MAIN ( 
	FILE_ID INT
	, LOAD_TS TIMESTAMP
	, DT DATE
	, PLANT_PRODUCT_ID VARCHAR(64)
	, FACTORY VARCHAR(12)
	, PLANT VARCHAR(12)
	, PRODUCT VARCHAR(64)
	, BP NUMERIC(18, 5)
	, PLAN NUMERIC(18, 5)
	, PPR NUMERIC(18, 5)
	, FORECAST NUMERIC(18, 5)
	, FACT NUMERIC(18, 5)
	, BP_C NUMERIC(18, 5)
	, PLAN_C NUMERIC(18, 5)
	, PPR_C NUMERIC(18, 5) 
	, FORECAST_C NUMERIC(18, 5)
	, FACT_C NUMERIC(18, 5)
	, DATE_DAY_BEFORE DATE
	, FACT_DB NUMERIC(18, 5)
	, FACT_C_DB NUMERIC(18, 5)
	, DATE_MONTH_BEFORE DATE
	, BP_MB NUMERIC(18, 5)
	, PLAN_MB NUMERIC(18, 5)
	, PPR_MB NUMERIC(18, 5)
	, FORECAST_MB NUMERIC(18, 5)
	, FACT_MB NUMERIC(18, 5)
	, BP_C_MB NUMERIC(18, 5)
	, PLAN_C_MB NUMERIC(18, 5)
	, PPR_C_MB NUMERIC(18, 5)
	, FORECAST_C_MB NUMERIC(18, 5)
	, FACT_C_MB NUMERIC(18, 5)
	, DATE_YEAR_BEFORE DATE
	, BP_YB NUMERIC(18, 5)
	, PLAN_YB NUMERIC(18, 5)
	, PPR_YB NUMERIC(18, 5)
	, FORECAST_YB NUMERIC(18, 5)
	, FACT_YB NUMERIC(18, 5)
	, BP_C_YB NUMERIC(18, 5)
	, PLAN_C_YB NUMERIC(18, 5)
	, PPR_C_YB NUMERIC(18, 5)
	, FORECAST_C_YB NUMERIC(18, 5)
	, FACT_C_YB NUMERIC(18, 5)
)
ORDER BY DT, PLANT_PRODUCT_ID 
SEGMENTED BY HASH(DT, PLANT_PRODUCT_ID) ALL NODES 
;