CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_BASE AS
SELECT 
	dds.FILE_ID
	, dds.LOAD_TS
	, dds.DT
	, dds.ID_PLANT_PRODUCT
	, dds.FACTORY
	, dds.PLANT
	, dds.PRODUCT
	, CASE 
		WHEN dds.PRODUCT IN ('С3+/ПНГ', 'С3+/СОГ', 'УВС') THEN NULL
		WHEN COUNT(BP) OVER (PARTITION BY DATE_PART('YEAR', DT), DATE_PART('MONTH', DT), dds.ID_PLANT_PRODUCT) > 27 THEN BP
		WHEN COUNT(BP) OVER (PARTITION BY DATE_PART('YEAR', DT), DATE_PART('MONTH', DT), dds.ID_PLANT_PRODUCT) <= 27 THEN (SUM(BP) OVER (PARTITION BY DATE_PART('YEAR', DT), DATE_PART('MONTH', DT), dds.ID_PLANT_PRODUCT) / COUNT(DT) OVER (PARTITION BY DATE_PART('YEAR', DT), DATE_PART('MONTH', DT), dds.ID_PLANT_PRODUCT))::NUMERIC(18, 5) 		
		END AS BP
	, dds.PLAN
	, dds.PPR
	, dds.FORECAST
	, dds.FACT
FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC dds
;