CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC AS
SELECT 
	lk_pm.FILE_ID,
	lk_pm.LOAD_TS,
	hub_cl.DT,
	hub_pp.ID_PLANT_PRODUCT,	
	hst_ppr.PLANT,
	hst_ppr.PLANT_ENCRYPTED,
	hst_ppr.PRODUCT,
	hst_ppr.PLANT_PRODUCT,
	hst_ppr.PLANT_PRODUCT_ENCRYPTED,
	hst_ppr.FACTORY,	
	sat_pm.BP,
	sat_pm.PLAN,
	sat_pm.PPR,
	sat_pm.FORECAST,
	sat_pm.FACT
FROM ODS_OPERSVODKA.DDS_LK_PLANT_PRODUCT_METRIC lk_pm
	INNER JOIN ODS_OPERSVODKA.V_DDS_LST_PLANT_PRODUCT_METRIC sat_pm ON sat_pm.HK_DDS_LK_PLANT_PRODUCT_METRIC = lk_pm.HK_DDS_LK_PLANT_PRODUCT_METRIC	
	INNER JOIN ODS_OPERSVODKA.DDS_HUB_DATE hub_cl ON hub_cl.HK_DDS_HUB_DATE = lk_pm.HK_DDS_HUB_DATE
	RIGHT JOIN ODS_OPERSVODKA.DDS_HUB_PLANT_PRODUCT hub_pp ON hub_pp.HK_DDS_HUB_PLANT_PRODUCT = lk_pm.HK_DDS_HUB_PLANT_PRODUCT	
	INNER JOIN ODS_OPERSVODKA.V_DDS_HST_PLANT_PRODUCT_REFERENCE hst_ppr ON hst_ppr.HK_DDS_HUB_PLANT_PRODUCT = hub_pp.HK_DDS_HUB_PLANT_PRODUCT	
;