CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_DUMMY_CALENDAR AS
SELECT 
	hub_cal.FILE_ID,
	hub_cal.LOAD_TS,
	hub_cal.ID,
	hst_cal.DATE_TODAY,
	hst_cal.DATE_DAY_BEFORE,
	hst_cal.DATE_MONTH_BEFORE,
	hst_cal.DATE_YEAR_BEFORE
FROM ODS_OPERSVODKA.DDS_HUB_DUMMY_CALENDAR hub_cal
	INNER JOIN ODS_OPERSVODKA.V_DDS_HST_DUMMY_CALENDAR hst_cal ON hst_cal.HK_DDS_HUB_DUMMY_CALENDAR = hub_cal.HK_DDS_HUB_DUMMY_CALENDAR
;