CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_SOG AS
SELECT
	sog.FILE_ID
	, sog.LOAD_TS
	, sog.DT
	, rf.ID_PLANT_PRODUCT
	, rf.FACTORY
	, rf.PLANT
	, rf.PRODUCT
	, (sz.BP / NULLIF(sog.BP, 0) * 1000)::NUMERIC(18, 5) AS BP
	, (sz.PPR / NULLIF(sog.PPR, 0) * 1000)::NUMERIC(18, 5) AS PPR
	, (sz.PLAN / NULLIF(sog.PLAN, 0) * 1000)::NUMERIC(18, 5) AS PLAN
	, (sz.FORECAST / NULLIF(sog.FORECAST, 0) * 1000)::NUMERIC(18, 5) AS FORECAST
	, (sz.FACT / NULLIF(sog.FACT, 0) * 1000)::NUMERIC(18, 5) AS FACT
FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_BASE AS rf
	LEFT JOIN ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_BASE AS sog ON sog.plant = rf.plant AND sog.product = 'СОГ'
	LEFT JOIN ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_BASE AS sz ON sz.plant = rf.plant AND sz.product = 'С3+ в СОГ' AND sz.DT = sog.DT
WHERE rf.product = 'С3+/СОГ'
;