CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DM_OPER_STRAIT (
	FILE_ID INT
	, LOAD_TS TIMESTAMP
	, DT DATE
	, PLANT_PRODUCT_ID VARCHAR(64)
	, FACTORY VARCHAR(12)
	, PLANT VARCHAR(12)
	, PRODUCT VARCHAR(64)
	, BP NUMERIC(18, 5) 
	, PLAN NUMERIC(18, 5) 
	, PPR NUMERIC(18, 5)
	, FORECAST NUMERIC(18, 5) 
	, FACT NUMERIC(18, 5)
	, BP_C NUMERIC(18, 5)
	, PLAN_C NUMERIC(18, 5) 
	, PPR_C NUMERIC(18, 5)
	, FORECAST_C NUMERIC(18, 5)
	, FACT_C NUMERIC(18, 5)
	, PRIMARY KEY (DT, PLANT_PRODUCT_ID) ENABLED 
)
ORDER BY DT, PLANT_PRODUCT_ID 
SEGMENTED BY HASH(DT, PLANT_PRODUCT_ID) ALL NODES ;