CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_CALC AS 
SELECT 
	FILE_ID
	, LOAD_TS
	, DT
	, ID_PLANT_PRODUCT
	, FACTORY
	, PLANT
	, PRODUCT
	, BP
	, PPR
	, PLAN
	, FORECAST
	, FACT
FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_BASE
WHERE FILE_ID IS NOT NULL 
	UNION ALL SELECT FILE_ID, LOAD_TS, DT, ID_PLANT_PRODUCT, FACTORY, PLANT, PRODUCT, BP, PPR, PLAN, FORECAST, FACT FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_PNG
	UNION ALL SELECT FILE_ID, LOAD_TS, DT, ID_PLANT_PRODUCT, FACTORY, PLANT, PRODUCT, BP, PPR, PLAN, FORECAST, FACT FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_SOG
	UNION ALL SELECT FILE_ID, LOAD_TS, DT, ID_PLANT_PRODUCT, FACTORY, PLANT, PRODUCT, BP, PPR, PLAN, FORECAST, FACT FROM ODS_OPERSVODKA.V_DDS_PLANT_PRODUCT_METRIC_UVS 
;