INSERT INTO ODS_OPERSVODKA.DM_OPER_MAIN (
	FILE_ID
	, LOAD_TS
	, DT
	, PLANT_PRODUCT_ID
	, FACTORY
	, PLANT
	, PRODUCT
	, BP
	, PLAN
	, PPR
	, FORECAST
	, FACT
	, BP_C
	, PLAN_C
	, PPR_C
	, FORECAST_C
	, FACT_C
	, DATE_DAY_BEFORE
	, FACT_DB
	, FACT_C_DB
	, DATE_MONTH_BEFORE
	, BP_MB
	, PLAN_MB
	, PPR_MB
	, FORECAST_MB
	, FACT_MB
	, BP_C_MB
	, PLAN_C_MB
	, PPR_C_MB
	, FORECAST_C_MB
	, FACT_C_MB
	, DATE_YEAR_BEFORE
	, BP_YB
	, PLAN_YB
	, PPR_YB
	, FORECAST_YB
	, FACT_YB
	, BP_C_YB
	, PLAN_C_YB
	, PPR_C_YB
	, FORECAST_C_YB
	, FACT_C_YB
)
SELECT
	dds.FILE_ID
	, dds.LOAD_TS
	, dds.DT
	, dds.PLANT_PRODUCT_ID
	, dds.FACTORY
	, dds.PLANT
	, dds.PRODUCT
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.BP END AS BP
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.PLAN END AS PLAN
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.PPR END AS PPR
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.FORECAST END AS FORECAST
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.FACT END AS FACT
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.BP_C END AS BP_C
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.PLAN_C END AS PLAN_C
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.PPR_C END AS PPR_C
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.FORECAST_C END AS FORECAST_C
	, CASE WHEN cal.DATE_DAY_BEFORE IS NULL AND cal.DATE_YEAR_BEFORE IS NULL THEN NULL ELSE dds.FACT_C END AS FACT_C
	, cal.DATE_DAY_BEFORE
	, dayback.FACT AS FACT_DB
	, dayback.FACT_C AS FACT_C_DB
	, cal.DATE_MONTH_BEFORE
	, monthback.BP AS BP_MB
	, monthback.PLAN AS PLAN_MB
	, monthback.PPR AS PPR_MB
	, monthback.FORECAST AS FORECAST_MB
	, monthback.FACT AS FACT_MB
	, monthback.BP_C AS BP_C_MB
	, monthback.PLAN_C AS PLAN_C_MB
	, monthback.PPR_C AS PPR_C_MB
	, monthback.FORECAST_C AS FORECAST_C_MB
	, monthback.FACT_C AS FACT_C_MB
	, cal.DATE_YEAR_BEFORE, yearback.BP AS BP_YB
	, yearback.PLAN AS PLAN_YB
	, yearback.PPR AS PPR_YB
	, yearback.FORECAST AS FORECAST_YB
	, yearback.FACT AS FACT_YB
	, yearback.BP_C AS BP_C_YB
	, yearback.PLAN_C AS PLAN_C_YB
	, yearback.PPR_C AS PPR_C_YB
	, yearback.FORECAST_C AS FORECAST_C_YB
	, yearback.FACT_C AS FACT_C_YB	
FROM ODS_OPERSVODKA.DM_OPER_STRAIT AS dds 
	LEFT JOIN ODS_OPERSVODKA.V_DDS_DUMMY_CALENDAR AS cal ON cal.DATE_TODAY = dds.DT
	LEFT JOIN ODS_OPERSVODKA.DM_OPER_STRAIT AS dayback ON dayback.DT = cal.DATE_DAY_BEFORE AND dayback.PLANT_PRODUCT_ID = dds.PLANT_PRODUCT_ID
	LEFT JOIN ODS_OPERSVODKA.DM_OPER_STRAIT AS monthback ON monthback.DT = cal.DATE_MONTH_BEFORE AND monthback.PLANT_PRODUCT_ID = dds.PLANT_PRODUCT_ID
	LEFT JOIN ODS_OPERSVODKA.DM_OPER_STRAIT AS yearback ON yearback.DT = cal.DATE_YEAR_BEFORE AND yearback.PLANT_PRODUCT_ID = dds.PLANT_PRODUCT_ID 
;