INSERT INTO ODS_OPERSVODKA.DDS_HST_COMMENTS (
	HK_DDS_HUB_COMMENTS ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	SUBPLANT,
	COMMENT,
	TEMPERATURE
)
SELECT
	HK_DDS_HUB_COMMENTS ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	SUBPLANT,
	COMMENT,
	TEMPERATURE
FROM ODS_OPERSVODKA.V_STG_COMMENTS_DDS_HST_COMMENTS src
;
