CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.ODS_STG_HQ_REPORT (
	FILE_ID INTEGER NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	SRC_SYSTEM VARCHAR(64) NOT NULL DEFAULT 'SAP MII',
	SCENARIO VARCHAR(64) NOT NULL,
	BUSINESS_DT DATE NOT NULL DEFAULT GETDATE(),
	DT DATE NOT NULL,
	PLANT_PRODUCT_ID VARCHAR(64) NOT NULL,
	BP NUMERIC(18,5),
	PLAN NUMERIC(18,5),
	PPR NUMERIC(18,5),
	FORECAST NUMERIC(18,5),
	FACT NUMERIC(18,5),
	PRIMARY KEY (FILE_ID, DT, PLANT_PRODUCT_ID) DISABLED
)
ORDER BY
	FILE_ID,
	PLANT_PRODUCT_ID,
	DT
SEGMENTED BY HASH(MD5(PLANT_PRODUCT_ID::VARCHAR)) ALL NODES
PARTITION BY DT GROUP BY CALENDAR_HIERARCHY_DAY(DT, 1, 2)
;
