CREATE TABLE IF NOT EXISTS STG_OPERSVODKA.ETL_LOAD_LOG (
	LOAD_TS TIMESTAMP,
	MODE VARCHAR(64),
	OBJECT VARCHAR(256),
    STEP VARCHAR(256),
	ROWCOUNT INTEGER,
    STATUS VARCHAR(64),
	DESCRIPTION VARCHAR(2048)
)
ORDER BY LOAD_TS, OBJECT, STEP
UNSEGMENTED ALL NODES
;
