CREATE TABLE IF NOT EXISTS STG_OPERSVODKA.ETL_FILE_LOAD (
	FILE_ID AUTO_INCREMENT(1, 1, 1) NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	SRC_SYSTEM VARCHAR(128) NOT NULL,
	FILE_NAME VARCHAR(64) NOT NULL,
	BUSINESS_DT DATE NOT NULL,
	PRIMARY KEY (FILE_ID) ENABLED
)
ORDER BY
	FILE_ID ,
	SRC_SYSTEM ,
	FILE_NAME ,
	BUSINESS_DT
UNSEGMENTED ALL NODES
;
