CREATE OR REPLACE VIEW STG_OPERSVODKA.V_ETL_FILE_LOAD AS
SELECT
	FILE_ID ,
	LOAD_TS ,
	SRC_SYSTEM ,
	FILE_NAME ,
	BUSINESS_DT
FROM STG_OPERSVODKA.ETL_FILE_LOAD
LIMIT 1 OVER (PARTITION BY SRC_SYSTEM, FILE_NAME, BUSINESS_DT ORDER BY LOAD_TS DESC)
;
