INSERT INTO ODS_OPERSVODKA.DDS_LST_PLANT_PRODUCT_METRIC (
	HK_DDS_LK_PLANT_PRODUCT_METRIC ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	BP,
	PLAN,
	PPR,
	FORECAST,
	FACT
)
SELECT
	HK_DDS_LK_PLANT_PRODUCT_METRIC ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	BP,
	PLAN,
	PPR,
	FORECAST,
	FACT
FROM ODS_OPERSVODKA.V_STG_STG_HQ_REPORT_DDS_LST_PLANT_PRODUCT_METRIC src
;
