CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_HST_COMMENTS (
	HK_DDS_HUB_COMMENTS VARCHAR(32) NOT NULL CONSTRAINT HK_DDS_HUB_COMMENTS REFERENCES ODS_OPERSVODKA.DDS_HUB_COMMENTS (HK_DDS_HUB_COMMENTS) ,
	FILE_ID INTEGER NOT NULL ,
	LOAD_TS TIMESTAMP NOT NULL ,
	HASHDIFF VARCHAR(32) NOT NULL ,
	PLANT VARCHAR(12),
	SUBPLANT VARCHAR(12),
	COMMENT VARCHAR(12000),
	TEMPERATURE NUMERIC(8,2) ,
	PRIMARY KEY (HK_DDS_HUB_COMMENTS, HASHDIFF) ENABLED
)
ORDER BY
	HK_DDS_HUB_COMMENTS ,
	LOAD_TS
SEGMENTED BY HASH(HK_DDS_HUB_COMMENTS) ALL NODES
;
