CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_HST_COMMENTS AS
SELECT
	HK_DDS_HUB_COMMENTS ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	SUBPLANT,
	COMMENT,
	TEMPERATURE
FROM ODS_OPERSVODKA.DDS_HST_COMMENTS
LIMIT 1 OVER (PARTITION BY HK_DDS_HUB_COMMENTS ORDER BY LOAD_TS DESC)
;
