INSERT INTO ODS_OPERSVODKA.DDS_HUB_COMMENTS (
	HK_DDS_HUB_COMMENTS ,
	FILE_ID ,
	LOAD_TS ,
	ID,
	DT
)
SELECT
	src.HK_DDS_HUB_COMMENTS ,
	src.FILE_ID ,
	src.LOAD_TS ,
	src.ID,
	src.DT
FROM ODS_OPERSVODKA.V_STG_COMMENTS_DDS_HUB_COMMENTS src
;
