CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_STG_DUMMY_CALENDAR_DDS_HUB_DUMMY_CALENDAR AS
SELECT DISTINCT
	MD5(TRIM(src.ID::VARCHAR)) AS HK_DDS_HUB_DUMMY_CALENDAR ,
	fl.FILE_ID ,
	fl.LOAD_TS ,
	src.ID
FROM STG_OPERSVODKA.STG_DUMMY_CALENDAR src
	INNER JOIN STG_OPERSVODKA.V_ETL_FILE_LOAD fl
			ON fl.SRC_SYSTEM = src.SRC_SYSTEM
				AND fl.FILE_NAME = src.SCENARIO
				AND fl.BUSINESS_DT = src.BUSINESS_DT
	LEFT JOIN ODS_OPERSVODKA.DDS_HUB_DUMMY_CALENDAR trg
		ON MD5(TRIM(src.ID::VARCHAR)) = trg.HK_DDS_HUB_DUMMY_CALENDAR
WHERE trg.HK_DDS_HUB_DUMMY_CALENDAR IS NULL
;
