CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_HUB_DUMMY_CALENDAR (
	HK_DDS_HUB_DUMMY_CALENDAR VARCHAR(32) NOT NULL,
	FILE_ID INTEGER NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	ID INTEGER NOT NULL,
	PRIMARY KEY (HK_DDS_HUB_DUMMY_CALENDAR) ENABLED
)
ORDER BY HK_DDS_HUB_DUMMY_CALENDAR
SEGMENTED BY HASH(HK_DDS_HUB_DUMMY_CALENDAR) ALL NODES
;
