CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_LST_PLANT_PRODUCT_METRIC (
	HK_DDS_LK_PLANT_PRODUCT_METRIC VARCHAR(32) NOT NULL CONSTRAINT HK_DDS_LK_PLANT_PRODUCT_METRIC REFERENCES ODS_OPERSVODKA.DDS_LK_PLANT_PRODUCT_METRIC (HK_DDS_LK_PLANT_PRODUCT_METRIC) ,
	FILE_ID INTEGER NOT NULL ,
	LOAD_TS TIMESTAMP NOT NULL ,
	HASHDIFF VARCHAR(32) NOT NULL ,
	BP NUMERIC(18,5),
	PLAN NUMERIC(18,5),
	PPR NUMERIC(18,5),
	FORECAST NUMERIC(18,5),
	FACT NUMERIC(18,5) ,
	PRIMARY KEY (HK_DDS_LK_PLANT_PRODUCT_METRIC, HASHDIFF) ENABLED
)
ORDER BY
	HK_DDS_LK_PLANT_PRODUCT_METRIC ,
	LOAD_TS
SEGMENTED BY HASH(HK_DDS_LK_PLANT_PRODUCT_METRIC) ALL NODES
;
