CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_LST_PLANT_PRODUCT_METRIC AS
SELECT
	HK_DDS_LK_PLANT_PRODUCT_METRIC ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	BP,
	PLAN,
	PPR,
	FORECAST,
	FACT
FROM ODS_OPERSVODKA.DDS_LST_PLANT_PRODUCT_METRIC
LIMIT 1 OVER (PARTITION BY HK_DDS_LK_PLANT_PRODUCT_METRIC ORDER BY LOAD_TS DESC)
;
