DROP TABLE IF EXISTS STG_OPERSVODKA.STG_DUMMY_CALENDAR ;

CREATE TABLE IF NOT EXISTS STG_OPERSVODKA.STG_DUMMY_CALENDAR (
	SRC_SYSTEM VARCHAR(64) NOT NULL DEFAULT 'EXCEL FILE',
	SCENARIO VARCHAR(64) NOT NULL DEFAULT 'GENERATED CALENDAR',
	BUSINESS_DT DATE NOT NULL DEFAULT GETDATE(),
	ID INTEGER NOT NULL,
	DATE_TODAY DATE,
	DATE_DAY_BEFORE DATE,
	DATE_MONTH_BEFORE DATE,
	DATE_YEAR_BEFORE DATE
)
ORDER BY ID,
	DATE_TODAY
UNSEGMENTED ALL NODES
;
