CREATE OR REPLACE VIEW ODS_OPERSVODKA.V_DDS_HST_PLANT_PRODUCT_REFERENCE AS
SELECT
	HK_DDS_HUB_PLANT_PRODUCT ,
	FILE_ID ,
	LOAD_TS ,
	HASHDIFF ,
	PLANT,
	PLANT_ENCRYPTED,
	PRODUCT,
	PLANT_PRODUCT,
	PLANT_PRODUCT_ENCRYPTED,
	FACTORY
FROM ODS_OPERSVODKA.DDS_HST_PLANT_PRODUCT_REFERENCE
LIMIT 1 OVER (PARTITION BY HK_DDS_HUB_PLANT_PRODUCT ORDER BY LOAD_TS DESC)
;
