CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_HST_PLANT_PRODUCT_REFERENCE (
	HK_DDS_HUB_PLANT_PRODUCT VARCHAR(32) NOT NULL CONSTRAINT HK_DDS_HUB_PLANT_PRODUCT REFERENCES ODS_OPERSVODKA.DDS_HUB_PLANT_PRODUCT (HK_DDS_HUB_PLANT_PRODUCT) ,
	FILE_ID INTEGER NOT NULL ,
	LOAD_TS TIMESTAMP NOT NULL ,
	HASHDIFF VARCHAR(32) NOT NULL ,
	PLANT VARCHAR(12),
	PLANT_ENCRYPTED VARCHAR(12),
	PRODUCT VARCHAR(64),
	PLANT_PRODUCT VARCHAR(64),
	PLANT_PRODUCT_ENCRYPTED VARCHAR(64),
	FACTORY VARCHAR(12) ,
	PRIMARY KEY (HK_DDS_HUB_PLANT_PRODUCT, HASHDIFF) ENABLED
)
ORDER BY
	HK_DDS_HUB_PLANT_PRODUCT ,
	LOAD_TS
SEGMENTED BY HASH(HK_DDS_HUB_PLANT_PRODUCT) ALL NODES
;
