INSERT INTO ODS_OPERSVODKA.DDS_HUB_DATE (
	HK_DDS_HUB_DATE ,
	FILE_ID ,
	LOAD_TS ,
	DT
)
SELECT
	src.HK_DDS_HUB_DATE ,
	src.FILE_ID ,
	src.LOAD_TS ,
	src.DT
FROM ODS_OPERSVODKA.V_STG_STG_HQ_REPORT_DDS_HUB_DATE src
;
