CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DM_DQ_TEMP(
FILE_ID 			INTEGER,
CHECK_NUMBER		INTEGER,
DT					DATE,
PLANT_PRODUCT_ID	VARCHAR(64),
FACTORY				VARCHAR(64),
PLANT				VARCHAR(64),
PRODUCT				VARCHAR(64),
TYPE				VARCHAR(64),
VALUE				NUMERIC(18,5),
B_TYPE				VARCHAR(64),
B_VALUE				NUMERIC(18,5),
DELTA				NUMERIC(18,5),
COMMENT				VARCHAR(1024),
ERR_TYPE			VARCHAR(64), 
PRIMARY KEY			(CHECK_NUMBER, DT, PLANT_PRODUCT_ID, TYPE))
ORDER BY CHECK_NUMBER, DT, PLANT_PRODUCT_ID UNSEGMENTED ALL NODES;