CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DM_DQ_MAIN(
ID 					AUTO_INCREMENT(1, 1, 1),
CHECK_NAME			VARCHAR(64),
CHECK_TYPE 			VARCHAR(64),
CHECK_NUMBER		INTEGER,
DT					DATE,
PLANT_PRODUCT_ID	VARCHAR(64) ,
FACTORY				VARCHAR(64) ,
PLANT				VARCHAR(64) ,
PRODUCT				VARCHAR(64) ,
TYPE				VARCHAR(64) ,
VALUE				NUMERIC(18,5),
B_TYPE				VARCHAR(64) ,
B_VALUE				NUMERIC(18,5),
DELTA				NUMERIC(18,5),
COMMENT				VARCHAR(1024) ,
ERR_TYPE			VARCHAR(64),
PRIMARY KEY			(ID))
ORDER BY DT, CHECK_NUMBER, PLANT_PRODUCT_ID, TYPE UNSEGMENTED ALL NODES;
