INSERT INTO ODS_OPERSVODKA.DDS_HUB_PLANT_PRODUCT (
	HK_DDS_HUB_PLANT_PRODUCT ,
	FILE_ID ,
	LOAD_TS ,
	ID_PLANT_PRODUCT
)
SELECT
	src.HK_DDS_HUB_PLANT_PRODUCT ,
	src.FILE_ID ,
	src.LOAD_TS ,
	src.ID_PLANT_PRODUCT
FROM ODS_OPERSVODKA.V_STG_REFERENCE_DDS_HUB_PLANT_PRODUCT src
;
