CREATE TABLE IF NOT EXISTS ODS_OPERSVODKA.DDS_LK_PLANT_PRODUCT_METRIC (
	HK_DDS_LK_PLANT_PRODUCT_METRIC VARCHAR(32) NOT NULL,
	HK_DDS_HUB_PLANT_PRODUCT VARCHAR(32) NOT NULL CONSTRAINT FK_DDS_HUB_PLANT_PRODUCT REFERENCES ODS_OPERSVODKA.DDS_HUB_PLANT_PRODUCT(HK_DDS_HUB_PLANT_PRODUCT),
	HK_DDS_HUB_DATE VARCHAR(32) NOT NULL CONSTRAINT FK_DDS_HUB_DATE REFERENCES ODS_OPERSVODKA.DDS_HUB_DATE(HK_DDS_HUB_DATE),
	FILE_ID INTEGER NOT NULL,
	LOAD_TS TIMESTAMP NOT NULL,
	PRIMARY KEY (HK_DDS_LK_PLANT_PRODUCT_METRIC) ENABLED
)
ORDER BY HK_DDS_LK_PLANT_PRODUCT_METRIC
SEGMENTED BY HASH(HK_DDS_LK_PLANT_PRODUCT_METRIC) ALL NODES ;
;
