STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_COMMENTS = VerticaOperatorExtended(
    dag=dag,
    task_id='STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_COMMENTS',
    sql='DWH/OPERSVODKA/1-STG_COMMENTS/TRUNCATE/STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_COMMENTS.sql',
    log_meta={
        'log_table' : 'OPERSVOD_STG.ETL_LOAD_LOG',
        'stage' : 'TRUNCATE',
        'obj' : 'STG_COMMENTS',
        'step' : 'STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_COMMENTS',
        'rowcount' : '',
        'status' : 'OK',
        'descr' : 'TRUNCATE STAGE TABLE : STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_COMMENTS.sql'
    }
)

STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_DUMMY_CALENDAR = VerticaOperatorExtended(
    dag=dag,
    task_id='STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_DUMMY_CALENDAR',
    sql='DWH/OPERSVODKA/1-STG_DUMMY_CALENDAR/TRUNCATE/STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_DUMMY_CALENDAR.sql',
    log_meta={
        'log_table' : 'OPERSVOD_STG.ETL_LOAD_LOG',
        'stage' : 'TRUNCATE',
        'obj' : 'STG_DUMMY_CALENDAR',
        'step' : 'STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_DUMMY_CALENDAR',
        'rowcount' : '',
        'status' : 'OK',
        'descr' : 'TRUNCATE STAGE TABLE : STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_DUMMY_CALENDAR.sql'
    }
)

STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_REFERENCE = VerticaOperatorExtended(
    dag=dag,
    task_id='STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_REFERENCE',
    sql='DWH/OPERSVODKA/1-STG_REFERENCE/TRUNCATE/STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_REFERENCE.sql',
    log_meta={
        'log_table' : 'OPERSVOD_STG.ETL_LOAD_LOG',
        'stage' : 'TRUNCATE',
        'obj' : 'STG_REFERENCE',
        'step' : 'STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_REFERENCE',
        'rowcount' : '',
        'status' : 'OK',
        'descr' : 'TRUNCATE STAGE TABLE : STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_REFERENCE.sql'
    }
)

STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_STG_HQ_REPORT = VerticaOperatorExtended(
    dag=dag,
    task_id='STG_OPERSVODKA_TRUNCATE_STG_OPERSVODKA_STG_STG_HQ_REPORT',
    sql='DWH/OPERSVODKA/1-STG_STG_HQ_REPORT/TRUNCATE/STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_STG_HQ_REPORT.sql',
    log_meta={
        'log_table' : 'OPERSVOD_STG.ETL_LOAD_LOG',
        'stage' : 'TRUNCATE',
        'obj' : 'STG_STG_HQ_REPORT',
        'step' : 'STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_STG_HQ_REPORT',
        'rowcount' : '',
        'status' : 'OK',
        'descr' : 'TRUNCATE STAGE TABLE : STG_OPERSVODKA.TRUNCATE_STG_OPERSVODKA.STG_STG_HQ_REPORT.sql'
    }
)

